// Generated by CoffeeScript 1.3.3

/*
@file main.coffee

@brief Main file for our server(s)
@author Lucas Ray (ltray)
*/


(function() {
  var HTTPRequestServer, SocketServer, main;

  HTTPRequestServer = require('./http_request_server');

  SocketServer = require('./socket_server');

  main = function() {
    /*
      @brief Main function.
    */

    var http_server, socket_server;
    http_server = new HTTPRequestServer(process.env.PORT || 8080);
    socket_server = new SocketServer(3000);
    http_server.listen();
    return socket_server.listen();
  };

  main();

}).call(this);
